# Generated by Django 3.2.8 on 2021-10-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userxmlfile',
            old_name='user',
            new_name='owner',
        ),
    ]
