# Generated by Django 3.2.8 on 2021-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_rename_user_userxmlfile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userxmlfile',
            name='url',
            field=models.TextField(),
        ),
    ]
